Repository jboss-container-images/jboss-eap-7-openshift-image, pull requests merged in 2018-10, with the labels that each got.

#144 [CLOUD-2432] Update EAP CD templates to use edge TLS
  templates/eap-cd-amq-persistent-s2i.json
  templates/eap-cd-amq-s2i.json
  templates/eap-cd-basic-s2i.json
  templates/eap-cd-https-s2i.json
  templates/eap-cd-mongodb-persistent-s2i.json
  templates/eap-cd-mongodb-s2i.json
  templates/eap-cd-mysql-persistent-s2i.json
  templates/eap-cd-mysql-s2i.json
  templates/eap-cd-postgresql-persistent-s2i.json
  templates/eap-cd-postgresql-s2i.json
  templates/eap-cd-sso-s2i.json
  templates/eap-cd-starter-s2i.json
  templates/eap-cd-third-party-db-s2i.json
  templates/eap-cd-tx-recovery-s2i.json
Labels: Needs Review, QE

#150 revert registry change until docs are corrected
  templates/eap-cd-image-stream.json
Labels: Needs Review

#161 [CLOUD-2908] - add version to template openshift.io/display-name
  templates/eap-cd-amq-persistent-s2i.json
  templates/eap-cd-amq-s2i.json
  templates/eap-cd-basic-s2i.json
  templates/eap-cd-https-s2i.json
  templates/eap-cd-image-stream.json
  templates/eap-cd-mongodb-persistent-s2i.json
  templates/eap-cd-mongodb-s2i.json
  templates/eap-cd-mysql-persistent-s2i.json
  templates/eap-cd-mysql-s2i.json
  templates/eap-cd-postgresql-persistent-s2i.json
  templates/eap-cd-postgresql-s2i.json
  templates/eap-cd-sso-s2i.json
  templates/eap-cd-starter-s2i.json
  templates/eap-cd-third-party-db-s2i.json
  templates/eap-cd-tx-recovery-postgresql-s2i.json
  templates/eap-cd-tx-recovery-s2i.json
Labels: Approved, Dev, QE

#162 [CLOUD-2786] Install the legacy activemq-rar.rar in case the app want…
  image.yaml
Labels: Approved, Dev

#149 CLOUD-2758 - [EAP71] Update jgroups AUTH and SYM_ENCRYPT to use non deprecated configurations
  dev-overrides.yaml
  image.yaml
Labels: Approved, Dev, QE

#155 [CLOUD-2907] review usage of hidden label on EAP CD templates.
  templates/eap-cd-https-s2i.json
  templates/eap-cd-mongodb-persistent-s2i.json
  templates/eap-cd-third-party-db-s2i.json
  templates/eap-cd-tx-recovery-s2i.json
Labels: Approved, Dev

#157 [CLOUD-2728] Integrate the jboss.eap.config.tracing module
  image.yaml
Labels: Approved, Dev, QE

#146 CLOUD-2788 / CLOUD-2546 - support for upstream KUBE_PING and DNS_PING
  docs/templates/eap-cd-amq-persistent-s2i.adoc
  docs/templates/eap-cd-amq-s2i.adoc
  docs/templates/eap-cd-basic-s2i.adoc
  docs/templates/eap-cd-https-s2i.adoc
  docs/templates/eap-cd-mongodb-persistent-s2i.adoc
  docs/templates/eap-cd-mongodb-s2i.adoc
  docs/templates/eap-cd-mysql-persistent-s2i.adoc
  docs/templates/eap-cd-mysql-s2i.adoc
  docs/templates/eap-cd-postgresql-persistent-s2i.adoc
  docs/templates/eap-cd-postgresql-s2i.adoc
  docs/templates/eap-cd-sso-s2i.adoc
  docs/templates/eap-cd-starter-s2i.adoc
  docs/templates/eap-cd-third-party-db-s2i.adoc
  docs/templates/eap-cd-tx-recovery-s2i.adoc
  gen_template_docs.py
  template.adoc.in
Labels: Approved, Dev, QE

#158 CLOUD-2691 - Change container family name from jboss-eap-7-tech-preview to jboss-eap-7 and use the --tech-preview flag when building
  .gitignore
  cp-overrides.yaml
  dev-overrides.yaml
  image.yaml
  rel-overrides.yaml
  tests/arq/README.md
  tests/arq/pom.xml
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapBasicTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapClusteringTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapDbTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapHttpsTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapPersistentTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/TodoList.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDClusteringTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDMongoDbPersistentTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDMongoDbTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDMysqlPersistentTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDMysqlTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDPostgresqlPersistentTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eapcd/EapCDPostgresqlTest.java
  tests/arq/src/test/resources/arquillian.xml
Labels: Approved, Dev, QE

#151 [CLOUD-2889] Configure templates to turn on incremental builds
  templates/eap-cd-amq-persistent-s2i.json
  templates/eap-cd-amq-s2i.json
  templates/eap-cd-basic-s2i.json
  templates/eap-cd-https-s2i.json
  templates/eap-cd-mongodb-persistent-s2i.json
  templates/eap-cd-mongodb-s2i.json
  templates/eap-cd-mysql-persistent-s2i.json
  templates/eap-cd-mysql-s2i.json
  templates/eap-cd-postgresql-persistent-s2i.json
  templates/eap-cd-postgresql-s2i.json
  templates/eap-cd-sso-s2i.json
  templates/eap-cd-starter-s2i.json
  templates/eap-cd-third-party-db-s2i.json
  templates/eap-cd-tx-recovery-s2i.json
Labels: Approved, Dev, QE

#165 [CLOUD-2982] Port EAP CD changes since EAP 7.2 Beta image to the eap72-dev branch
  .gitignore
  cp-overrides.yaml
  dev-overrides.yaml
  docs/templates/eap72-amq-persistent-s2i.adoc
  docs/templates/eap72-amq-s2i.adoc
  docs/templates/eap72-basic-s2i.adoc
  docs/templates/eap72-https-s2i.adoc
  docs/templates/eap72-mongodb-persistent-s2i.adoc
  docs/templates/eap72-mongodb-s2i.adoc
  docs/templates/eap72-mysql-persistent-s2i.adoc
  docs/templates/eap72-mysql-s2i.adoc
  docs/templates/eap72-postgresql-persistent-s2i.adoc
  docs/templates/eap72-postgresql-s2i.adoc
  docs/templates/eap72-sso-s2i.adoc
  docs/templates/eap72-starter-s2i.adoc
  docs/templates/eap72-third-party-db-s2i.adoc
  docs/templates/eap72-tx-recovery-s2i.adoc
  gen_template_docs.py
  image.yaml
  rel-overrides.yaml
  template.adoc.in
  templates/eap72-amq-persistent-s2i.json
  templates/eap72-amq-s2i.json
  templates/eap72-basic-s2i.json
  templates/eap72-https-s2i.json
  templates/eap72-image-stream.json
  templates/eap72-mongodb-persistent-s2i.json
  templates/eap72-mongodb-s2i.json
  templates/eap72-mysql-persistent-s2i.json
  templates/eap72-mysql-s2i.json
  templates/eap72-postgresql-persistent-s2i.json
  templates/eap72-postgresql-s2i.json
  templates/eap72-sso-s2i.json
  templates/eap72-starter-s2i.json
  templates/eap72-third-party-db-s2i.json
  templates/eap72-tx-recovery-s2i.json
  tests/arq/README.md
  tests/arq/pom.xml
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapBasicTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapClusteringTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapDbTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapHttpsTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/EapPersistentTestBase.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/common/TodoList.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72BasicTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72ClusteringTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72HttpsTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72MongoDbPersistentTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72MongoDbTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72MysqlPersistentTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72MysqlTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72PostgresqlPersistentTest.java
  tests/arq/src/test/java/org/jboss/test/arquillian/ce/eap72/Eap72PostgresqlTest.java
  tests/arq/src/test/resources/arquillian.xml
  tests/arq/src/test/resources/log4j.properties
  tests/arq/src/test/resources/testrunner-pod.json
  tests/arq/src/test/resources/web.xml
Labels: Approved, Dev, QE

#168 [CLOUD-2999] Use AMQ 7.2 in the EAP CD templates
  templates/eap-cd-amq-persistent-s2i.json
  templates/eap-cd-amq-s2i.json
  templates/eap-cd-tx-recovery-s2i.json
Labels: Approved, Dev, QE

#169 [CLOUD-2995] Base on RHEL7 instead of openjdk + eap standalone image
  cp-overrides.yaml
  dev-overrides.yaml
  image.yaml
  rel-overrides.yaml
Labels: Approved, Dev, QE
